sources:
  - name: raw
    database: USER_DB_GORILLA
    schema: raw
    description: "Schema which stores raw data from ETL"
    tables:
      - name: weather_data_lab1
        identifier: weather_data_lab1
        description: "Weather data including date,location_name, latitude, longitude, temp_max, temp_min, temp_mean, weather_code"
  - name: analytics
    database: USER_DB_GORILLA
    schema: analytics
    description: "Schema storing analytics tables (ELT)"
    tables:
      - name: weather_summary
        identifier: weather_summary
        description: "Detailed weather summary including date,location_name, moving_avg, temp_anomaly"
